services:
  database:
    image: postgres:16.10-alpine3.22
    container_name: smmikod-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smmikod-app
    environment:
      NODE_ENV: production
      SERVER_PORT: ${SERVER_PORT:-5100}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: database
      IDENT_INTEGRATION_KEY: ${IDENT_INTEGRATION_KEY}
    ports:
      - '${SERVER_PORT:-5100}:5100'
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  # wordpress:
  #   image: wordpress
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     WORDPRESS_DB_HOST: wp-database
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #     WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  #   volumes:
  #     - wordpress:/var/www/html
  #   depends_on:
  #     - wp-database

  # wp-database:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
  #     MYSQL_USER: ${WORDPRESS_DB_USER}
  #     MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #     MYSQL_RANDOM_ROOT_PASSWORD: '1'
  #   volumes:
  #     - wp-database:/var/lib/mysql

volumes:
  postgres_data:
  # wordpress:
  # wp-database:
